# Generated by Django 2.2.3 on 2019-07-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=25)),
                ('ruc', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='UsuarioBBVA',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Proveedor')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id_cuenta', models.IntegerField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[(1, 'Pagado'), (2, 'No Pagado'), (3, 'Vencido')], max_length=15)),
                ('fecha_vencimiento', models.DateField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cliente')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Servicio')),
            ],
            options={
                'db_table': 'recibo',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id_cuenta_bancaria', models.AutoField(primary_key=True, serialize=False)),
                ('nro_cuenta', models.CharField(max_length=15)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cliente')),
            ],
            options={
                'db_table': 'cuenta_bancaria',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.UsuarioBBVA'),
        ),
    ]
