# Generated by Django 2.2.3 on 2019-07-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='id_cuenta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
