# Generated by Django 2.2.3 on 2019-07-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190719_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='estado',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('No Pagado', 'No Pagado'), ('Vencido', 'Vencido')], max_length=15),
        ),
    ]
