# Generated by Django 2.2.3 on 2019-07-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190719_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibo',
            old_name='id_cuenta',
            new_name='id_recibo',
        ),
    ]
